import {
  AlertTriangle,
  ShieldAlert,
  FileCheck2,
  Lock,
  ClipboardList,
  Wrench,
  GraduationCap,
  HardHat,
  SearchCheck,
  Siren,
  FireExtinguisher,
  TrendingUp,
  MessagesSquare,
  HeartPulse,
} from 'lucide-react';

// Config-driven module system. Every entry renders through ModulePage:
// list + stats + search + status filter + create/edit/delete forms.
// Field types: text, textarea, date, select, site, number, person.

const SEVERITIES = ['Low', 'Medium', 'High', 'Critical'];

export const MODULES = [
  {
    id: 'incidents',
    collection: 'incidents',
    label: 'Incidents',
    singular: 'Incident',
    icon: AlertTriangle,
    description: 'Report, investigate and close workplace incidents and near misses.',
    statuses: ['Open', 'Under Investigation', 'Closed'],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'site', label: 'Site', type: 'site', required: true },
      { key: 'date', label: 'Incident date', type: 'date', required: true },
      {
        key: 'category',
        label: 'Category',
        type: 'select',
        options: ['Injury', 'Near Miss', 'Property Damage', 'Environmental', 'Fire', 'Other'],
        required: true,
      },
      { key: 'severity', label: 'Severity', type: 'select', options: SEVERITIES, required: true },
      { key: 'location', label: 'Exact location', type: 'text' },
      { key: 'description', label: 'What happened?', type: 'textarea', required: true },
      { key: 'immediateAction', label: 'Immediate action taken', type: 'textarea' },
      { key: 'rootCause', label: 'Root cause (investigation)', type: 'textarea' },
    ],
    listColumns: ['title', 'site', 'date', 'severity', 'status'],
  },
  {
    id: 'riskAssessments',
    collection: 'riskAssessments',
    label: 'Risk Assessments',
    singular: 'Risk Assessment',
    icon: ShieldAlert,
    description: 'Identify hazards, evaluate risk and track control measures.',
    statuses: ['Draft', 'Active', 'Review Due', 'Archived'],
    fields: [
      { key: 'title', label: 'Activity / process', type: 'text', required: true },
      { key: 'site', label: 'Site', type: 'site', required: true },
      { key: 'date', label: 'Assessment date', type: 'date', required: true },
      { key: 'hazard', label: 'Hazard description', type: 'textarea', required: true },
      { key: 'likelihood', label: 'Likelihood (1-5)', type: 'number', min: 1, max: 5, required: true },
      { key: 'severityScore', label: 'Severity (1-5)', type: 'number', min: 1, max: 5, required: true },
      { key: 'controls', label: 'Existing controls', type: 'textarea' },
      { key: 'additionalControls', label: 'Additional controls required', type: 'textarea' },
      { key: 'reviewDate', label: 'Next review date', type: 'date' },
    ],
    listColumns: ['title', 'site', 'date', 'status'],
  },
  {
    id: 'ptwRecords',
    collection: 'ptwRecords',
    label: 'Permit to Work',
    singular: 'Permit',
    icon: FileCheck2,
    description: 'Issue and control permits for high-risk work activities.',
    statuses: ['Requested', 'Issued', 'Active', 'Closed', 'Cancelled'],
    fields: [
      { key: 'title', label: 'Work description', type: 'text', required: true },
      { key: 'site', label: 'Site', type: 'site', required: true },
      {
        key: 'permitType',
        label: 'Permit type',
        type: 'select',
        options: ['Hot Work', 'Confined Space', 'Working at Height', 'Electrical', 'Excavation', 'General'],
        required: true,
      },
      { key: 'date', label: 'Start date', type: 'date', required: true },
      { key: 'endDate', label: 'End date', type: 'date' },
      { key: 'contractor', label: 'Contractor / crew', type: 'text' },
      { key: 'precautions', label: 'Precautions & isolations', type: 'textarea' },
    ],
    listColumns: ['title', 'site', 'permitType', 'date', 'status'],
  },
  {
    id: 'lotoProcedures',
    collection: 'lotoProcedures',
    label: 'LOTO',
    singular: 'LOTO Procedure',
    icon: Lock,
    description: 'Lockout/tagout procedures for hazardous energy control.',
    statuses: ['Draft', 'Approved', 'In Use', 'Retired'],
    fields: [
      { key: 'title', label: 'Equipment / machine', type: 'text', required: true },
      { key: 'site', label: 'Site', type: 'site', required: true },
      {
        key: 'energySources',
        label: 'Energy sources',
        type: 'select',
        options: ['Electrical', 'Mechanical', 'Hydraulic', 'Pneumatic', 'Thermal', 'Chemical', 'Multiple'],
        required: true,
      },
      { key: 'isolationSteps', label: 'Isolation steps', type: 'textarea', required: true },
      { key: 'verification', label: 'Zero-energy verification', type: 'textarea' },
      { key: 'date', label: 'Effective date', type: 'date' },
    ],
    listColumns: ['title', 'site', 'energySources', 'status'],
  },
  {
    id: 'auditPlans',
    collection: 'auditPlans',
    label: 'Audits',
    singular: 'Audit',
    icon: ClipboardList,
    description: 'Plan and execute internal and external HSE audits.',
    statuses: ['Planned', 'In Progress', 'Completed', 'Overdue'],
    fields: [
      { key: 'title', label: 'Audit title', type: 'text', required: true },
      { key: 'site', label: 'Site', type: 'site', required: true },
      {
        key: 'auditType',
        label: 'Type',
        type: 'select',
        options: ['Internal', 'External', 'Regulatory', 'Supplier'],
        required: true,
      },
      { key: 'standard', label: 'Standard / scope', type: 'text' },
      { key: 'date', label: 'Scheduled date', type: 'date', required: true },
      { key: 'auditor', label: 'Lead auditor', type: 'person' },
      { key: 'findings', label: 'Findings summary', type: 'textarea' },
    ],
    listColumns: ['title', 'site', 'auditType', 'date', 'status'],
  },
  {
    id: 'capaActions',
    collection: 'capaActions',
    label: 'CAPA',
    singular: 'CAPA Action',
    icon: Wrench,
    description: 'Corrective and preventive actions from incidents, audits and inspections.',
    statuses: ['Open', 'In Progress', 'Completed', 'Overdue', 'Verified'],
    fields: [
      { key: 'title', label: 'Action description', type: 'text', required: true },
      { key: 'site', label: 'Site', type: 'site', required: true },
      {
        key: 'actionType',
        label: 'Type',
        type: 'select',
        options: ['Corrective', 'Preventive'],
        required: true,
      },
      { key: 'source', label: 'Source (incident, audit…)', type: 'text' },
      { key: 'owner', label: 'Action owner', type: 'person', required: true },
      { key: 'date', label: 'Due date', type: 'date', required: true },
      { key: 'evidence', label: 'Completion evidence', type: 'textarea' },
    ],
    listColumns: ['title', 'site', 'actionType', 'owner', 'date', 'status'],
  },
  {
    id: 'trainings',
    collection: 'trainings',
    label: 'Training',
    singular: 'Training',
    icon: GraduationCap,
    description: 'Schedule safety training and track attendance and competency.',
    statuses: ['Scheduled', 'Completed', 'Cancelled'],
    fields: [
      { key: 'title', label: 'Course title', type: 'text', required: true },
      { key: 'site', label: 'Site', type: 'site', required: true },
      { key: 'trainer', label: 'Trainer', type: 'person' },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'duration', label: 'Duration (hours)', type: 'number', min: 0 },
      { key: 'attendees', label: 'Attendees', type: 'textarea' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    listColumns: ['title', 'site', 'trainer', 'date', 'status'],
  },
  {
    id: 'contractors',
    collection: 'contractors',
    label: 'Contractors',
    singular: 'Contractor',
    icon: HardHat,
    description: 'Manage contractor companies, inductions and compliance documents.',
    statuses: ['Pending Approval', 'Approved', 'Suspended', 'Expired'],
    fields: [
      { key: 'title', label: 'Company name', type: 'text', required: true },
      { key: 'site', label: 'Primary site', type: 'site', required: true },
      { key: 'contactName', label: 'Contact person', type: 'text' },
      { key: 'contactEmail', label: 'Contact email', type: 'text' },
      { key: 'scope', label: 'Scope of work', type: 'textarea' },
      { key: 'date', label: 'Approval / induction date', type: 'date' },
      { key: 'insuranceExpiry', label: 'Insurance expiry', type: 'date' },
    ],
    listColumns: ['title', 'site', 'contactName', 'insuranceExpiry', 'status'],
  },
  {
    id: 'inspectionRecords',
    collection: 'inspectionRecords',
    label: 'Inspections',
    singular: 'Inspection',
    icon: SearchCheck,
    description: 'Routine workplace, equipment and housekeeping inspections.',
    statuses: ['Scheduled', 'Completed', 'Action Required'],
    fields: [
      { key: 'title', label: 'Inspection title', type: 'text', required: true },
      { key: 'site', label: 'Site', type: 'site', required: true },
      {
        key: 'area',
        label: 'Area / equipment',
        type: 'text',
        required: true,
      },
      { key: 'inspector', label: 'Inspector', type: 'person' },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'observations', label: 'Observations', type: 'textarea' },
      { key: 'actions', label: 'Actions raised', type: 'textarea' },
    ],
    listColumns: ['title', 'site', 'area', 'date', 'status'],
  },
  {
    id: 'mockDrills',
    collection: 'mockDrills',
    label: 'Mock Drills',
    singular: 'Mock Drill',
    icon: Siren,
    description: 'Emergency preparedness drills and evacuation exercises.',
    statuses: ['Planned', 'Completed', 'Cancelled'],
    fields: [
      { key: 'title', label: 'Drill scenario', type: 'text', required: true },
      { key: 'site', label: 'Site', type: 'site', required: true },
      {
        key: 'drillType',
        label: 'Type',
        type: 'select',
        options: ['Fire Evacuation', 'Spill Response', 'Medical Emergency', 'Rescue', 'Other'],
        required: true,
      },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'participants', label: 'Participants (count)', type: 'number', min: 0 },
      { key: 'evacuationTime', label: 'Evacuation time (minutes)', type: 'number', min: 0 },
      { key: 'learnings', label: 'Observations & learnings', type: 'textarea' },
    ],
    listColumns: ['title', 'site', 'drillType', 'date', 'status'],
  },
  {
    id: 'emergencyEquipment',
    collection: 'emergencyEquipment',
    label: 'Emergency Equipment',
    singular: 'Equipment Item',
    icon: FireExtinguisher,
    description: 'Registers and checks for extinguishers, alarms, PPE and first-aid.',
    statuses: ['Operational', 'Needs Service', 'Out of Service'],
    fields: [
      { key: 'title', label: 'Equipment', type: 'text', required: true },
      { key: 'site', label: 'Site', type: 'site', required: true },
      {
        key: 'equipmentType',
        label: 'Type',
        type: 'select',
        options: ['Fire Extinguisher', 'Fire Alarm', 'First Aid Kit', 'Eye Wash', 'Spill Kit', 'AED', 'Other'],
        required: true,
      },
      { key: 'location', label: 'Location', type: 'text', required: true },
      { key: 'date', label: 'Last inspection', type: 'date' },
      { key: 'nextDue', label: 'Next inspection due', type: 'date' },
    ],
    listColumns: ['title', 'site', 'equipmentType', 'location', 'nextDue', 'status'],
  },
  {
    id: 'improvements',
    collection: 'improvements',
    label: 'Improvements',
    singular: 'Improvement',
    icon: TrendingUp,
    description: 'Continuous improvement ideas and safety suggestions.',
    statuses: ['Submitted', 'Under Review', 'Approved', 'Implemented', 'Rejected'],
    fields: [
      { key: 'title', label: 'Improvement idea', type: 'text', required: true },
      { key: 'site', label: 'Site', type: 'site', required: true },
      { key: 'submittedBy', label: 'Submitted by', type: 'person' },
      { key: 'date', label: 'Date submitted', type: 'date' },
      { key: 'benefit', label: 'Expected benefit', type: 'textarea' },
      { key: 'description', label: 'Details', type: 'textarea' },
    ],
    listColumns: ['title', 'site', 'submittedBy', 'date', 'status'],
  },
  {
    id: 'consultations',
    collection: 'consultations',
    label: 'Consultations',
    singular: 'Consultation',
    icon: MessagesSquare,
    description: 'Worker participation: safety committees, toolbox talks and consultations.',
    statuses: ['Scheduled', 'Held', 'Minutes Published'],
    fields: [
      { key: 'title', label: 'Topic', type: 'text', required: true },
      { key: 'site', label: 'Site', type: 'site', required: true },
      {
        key: 'meetingType',
        label: 'Type',
        type: 'select',
        options: ['Safety Committee', 'Toolbox Talk', 'Worker Consultation', 'Management Review'],
        required: true,
      },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'attendees', label: 'Attendees', type: 'textarea' },
      { key: 'minutes', label: 'Minutes / outcomes', type: 'textarea' },
    ],
    listColumns: ['title', 'site', 'meetingType', 'date', 'status'],
  },
  {
    id: 'healthCases',
    collection: 'healthCases',
    label: 'Occupational Health',
    singular: 'Health Case',
    icon: HeartPulse,
    description: 'Occupational health surveillance, cases and return-to-work.',
    statuses: ['Open', 'Monitoring', 'Closed'],
    fields: [
      { key: 'title', label: 'Case reference', type: 'text', required: true },
      { key: 'site', label: 'Site', type: 'site', required: true },
      {
        key: 'caseType',
        label: 'Type',
        type: 'select',
        options: ['Health Surveillance', 'Occupational Illness', 'Ergonomic', 'Hearing', 'Respiratory', 'Other'],
        required: true,
      },
      { key: 'date', label: 'Date opened', type: 'date', required: true },
      { key: 'restrictions', label: 'Work restrictions', type: 'textarea' },
      { key: 'notes', label: 'Confidential notes', type: 'textarea' },
    ],
    listColumns: ['title', 'site', 'caseType', 'date', 'status'],
  },
];

export const moduleById = (id) => MODULES.find((m) => m.id === id);
